### ISSUE TITLE
可否将luci和package 放到一个文件夹

### ISSUE THREAD

**Issue by fuqiang03** [KunTengRom/kunteng-lede-17.01.4#2]
可否将luci和package 放到一个文件夹

**Comment by liudf0716** [comment]
目前还是分开的，编译前先要feeds update&install

**Comment by fuqiang03** [comment]
还有个问题
![qq 20171117134425](https://user-images.githubusercontent.com/26851715/32931171-b8885c6a-cb9d-11e7-82b6-a0499911b51b.png)
因为有些插件还需要依赖以前的so文件。例如，Transmission

**Comment by liudf0716** [comment]
收到

**Comment by fuqiang03** [comment]
so文件名被改了，会提示，文件不存在的

**Comment by fuqiang03** [comment]
so文件名被改了，其他需要依赖的插件会提示找不到。
