### ISSUE TITLE
缺了很多包

### ISSUE THREAD

**Issue by hxy8241** [KunTengRom/kunteng-lede-17.01.4#4]
是因为国内没镜像的缘故吗？

**Comment by liudf0716** [comment]
为了保证每个软件包的下载速度，没有直接用openwrt的package源，而且openwrt的package源太多了，很多其实不一定需要，就没引用

**Comment by liudf0716** [comment]
可以，我们只是用r7800做为demo说明，只要lede17.01.4支持的，这个sdk版本都支持，甚至他不支持的b70，我们也放进去支持了。

**Comment by yorkane** [comment]
现在lede和 openwrt 合并了，那么kunteng-lede是否等同于现在官网的openwrt ？只是下载源和不一样？

**Comment by liudf0716** [comment]
没区别，不同版本的叫法，可以理解为
