### ISSUE TITLE
Apfree_wifidog 编译错误

### ISSUE THREAD

**Issue by crackself** [KunTengRom/kunteng-lede-17.01.4#5]
用lede-17.01.4源码，同步日期2018-4-09
ar71xx / 4300V1平台。
错误提示：
`/source/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.16/lib/gcc/mips-openwrt-linux-musl/5.4.0/../../../../mips-openwrt-linux-musl/bin/ld: copy reloc against protected `__stack_chk_guard' is dangerous
CMakeFiles/wifidog.dir/simple_http.c.o: In function `evhttps_request':
simple_http.c:(.text+0x9ba): undefined reference to `bufferevent_openssl_set_allow_dirty_shutdown'
simple_http.c:(.text+0x9ca): undefined reference to `evhttp_connection_base_bufferevent_new'
CMakeFiles/wifidog.dir/https_server.c.o: In function `thread_https_server':
https_server.c:(.text+0x618): undefined reference to `evhttp_set_bevcb'
collect2: error: ld returned 1 exit status
src/CMakeFiles/wifidog.dir/build.make:823: recipe for target 'src/wifidog' failed
make[5]: *** [src/wifidog] Error 1`

**Comment by liudf0716** [comment]
看起来好像是libevent2的问题，编译libevent2了吗？

**Comment by crackself** [comment]
没有留意libevent2，我再试试

**Comment by crackself** [comment]
libevent2已经编译，确认不是这个原因

**Comment by liudf0716** [comment]
apfree wifidog使用的版本有修改吗？是否有修改package里面的makefile 呢？
话说我们一直在用，没发现编译有问题啊。

**Comment by crackself** [comment]
确实没有修改过，和官方仓库唯一差别是内核应用了fast_patch补丁

**Comment by liudf0716** [comment]
这几个缺失的函数都是libevent2 openssl的，你一定要确认是否选择了这个。
make menuconfig 看看

**Comment by liudf0716** [comment]
checking pkg-config is at least version 0.9.0... yes
configure: error: Invalid kernel source directory /lib/modules/4.9.80-v7+/source
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ipset依赖内核部分出问题了，要不你在一个完全干净的环境里再编译一下看看。

**Comment by liudf0716** [comment]
你是用我们这个lede sdk环境吗？还是你移植到其他版本的openwrt上了？

**Comment by crackself** [comment]
是用openwrt官方源码的编译得到的sdk

**Comment by liudf0716** [comment]
我说怎么会有这么多问题。
openwrt 不要在cc版本以下编译，ipset问题无解。
